"use client";

import { useState, useRef } from "react";
import { House } from "lucide-react";
import CountUp from "react-countup";
import dynamic from "next/dynamic";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/lib/supabase";
import emailjs from "emailjs-com";
import html2canvas from "html2canvas";

import GoogleSignIn
from "@/components/GoogleSignIn";

import {
  stateLocations,
} from "@/data/locations";

import {
  stateMultipliers,
  finishMultipliers,
  bedroomMultipliers,
  floorMultipliers,
  foundationMultipliers,
  unitMultipliers,
} from "@/data/multipliers";

import {
  buildingBaseCosts,
} from "@/data/buildingCosts";

import {
  buildingTypes,
} from "@/data/buildingTypes";

const PaystackButton = dynamic(
  async () =>
    (await import("react-paystack")).PaystackButton,
  {
    ssr: false,
  }
);

export default function Home() {
  const [projectName, setProjectName] = useState("");
  const [state, setState] = useState("");
  const resultRef = useRef<HTMLDivElement>(null);

  const [location, setLocation] = useState("");
  const [size, setSize] = useState("");

  const [sizeUnit, setSizeUnit] =
  useState("SQM");

  const [finish, setFinish] = useState("Standard");

  const [buildingCategory, setBuildingCategory] =
  useState("Bungalow");

  const [buildingSubtype, setBuildingSubtype] =
  useState("Detached Bungalow");

const [bedrooms, setBedrooms] =
  useState(3);

  const [floors, setFloors] =
  useState(1);

  const [units, setUnits] =
  useState(1);

  const [result, setResult] = useState<number | null>(null);
  const [showResult, setShowResult] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);

  const [emailModalType, setEmailModalType] =
  useState("basic");

  const [paymentAmount, setPaymentAmount] =
  useState(3000);

  const [addFence, setAddFence] =
  useState(false);

const [addBQ, setAddBQ] =
  useState(false);

const [addPool, setAddPool] =
  useState(false);

const [luxuryRoof, setLuxuryRoof] =
  useState(false);

  const [monthlyIncome, setMonthlyIncome] =
  useState("");

const [currentSavings, setCurrentSavings] =
  useState("");

const [email, setEmail] = useState("");
const publicKey: string = "pk_test_5354773176b3c1334a414f9c92e9c5aee9fff2f1";

const amount = paymentAmount * 100;

const sendReportEmail = async () => {

  try {

    await emailjs.send(

      "service_j306r3r",

      "template_h2q99lh",

      {
        user_name: projectName,

        project_name: projectName,

        project_cost:
          `₦${result?.toLocaleString()}`,

        user_email: email,
      },

      "oHAwUeN51GdhHQvnW"
    );

    console.log("Email sent");

  } catch (error) {

    console.log(error);

  }

};

const saveReport = async () => {

const sendReportEmail = async () => {

  // emailjs code

};

const saveReport = async () => {

  // REAL supabase code

};

  const { error } =
    await supabase.from("reports").insert([
      {
        project_name: projectName,

        location,

        finish,

        estimated_cost: result,

        user_email: email,
      },
    ]);

  if (error) {

    console.log(error);

    alert("Failed to save report");

  } else {

    console.log("Report saved");

  }

};

const generatePDF = () => {

  const doc = new jsPDF();

  // ===== COVER PAGE =====

  doc.setFillColor(15, 17, 21);

  doc.rect(0, 0, 210, 297, "F");

  doc.setTextColor(212, 168, 79);

  doc.setFontSize(30);

  doc.text(
    "My House Cost NG",
    20,
    60
  );

  doc.setTextColor(255);

  doc.setFontSize(22);

  doc.text(
    "Professional Building Cost Report",
    20,
    85
  );

  doc.setFontSize(14);

  doc.setTextColor(180);

  doc.text(
    `Project: ${projectName}`,
    20,
    110
  );

  doc.text(
    `Location: ${location}`,
    20,
    122
  );

  doc.text(
    `Finish Level: ${finish}`,
    20,
    134
  );

  doc.text(
    `Estimated Cost: ₦${result?.toLocaleString()}`,
    20,
    146
  );

  doc.setTextColor(120);

  doc.text(
    "Generated by My House Cost NG",
    20,
    260
  );

  // ===== PAGE 2 =====

  doc.addPage();

  doc.setFontSize(24);

  doc.setTextColor(0);

  doc.text(
    "Executive Summary",
    20,
    30
  );

  doc.setFontSize(12);

  doc.text(
    `This report provides a professional cost estimate for the proposed construction project located in ${location}.`,
    20,
    50,
    {
      maxWidth: 170,
    }
  );

  // ===== COST BREAKDOWN TABLE =====

  autoTable(doc, {
    startY: 80,

    head: [["Category", "Estimated Cost"]],

    body: [
      [
        "Foundation",
        `₦${foundation.toLocaleString()}`
      ],

      [
        "Structure",
        `₦${structure.toLocaleString()}`
      ],

      [
        "Finishes",
        `₦${finishes.toLocaleString()}`
      ],

      [
        "Services",
        `₦${services.toLocaleString()}`
      ],
    ],

    headStyles: {
      fillColor: [15, 17, 21],
    },
  });

  // ===== PAGE 3 =====

  doc.addPage();

  doc.setFontSize(24);

  doc.text(
    "Detailed BOQ Breakdown",
    20,
    30
  );

  autoTable(doc, {
    startY: 50,

    head: [["Item", "Estimated Cost"]],

    body: [
      ["Excavation", "₦850,000"],

      ["Concrete", "₦1,400,000"],

      ["Roofing", "₦2,800,000"],

      ["Electrical", "₦1,200,000"],

      ["Plumbing", "₦950,000"],

      ["Tiles", "₦1,500,000"],
    ],

    headStyles: {
      fillColor: [212, 168, 79],
    },
  });

  // ===== PAGE 4 =====

  doc.addPage();

  doc.setFontSize(24);

  doc.text(
    "Construction Timeline",
    20,
    30
  );

  autoTable(doc, {
    startY: 50,

    head: [["Phase", "Estimated Timeline"]],

    body: [
      ["Foundation", "Month 1"],

      ["Structure", "Month 2"],

      ["Roofing", "Month 3"],

      ["MEP Services", "Month 4"],

      ["Finishes", "Month 5"],

      ["External Works", "Month 6"],
    ],

    headStyles: {
      fillColor: [15, 17, 21],
    },
  });

  // ===== FINAL PAGE =====

  doc.addPage();

  doc.setFontSize(24);

  doc.text(
    "Professional Recommendation",
    20,
    30
  );

  doc.setFontSize(12);

  doc.text(
    `Using ${finish} finishing significantly impacts project cost and delivery timeline. Proper planning and contractor selection is strongly recommended.`,
    20,
    50,
    {
      maxWidth: 170,
    }
  );

  doc.text(
    "Thank you for using My House Cost NG.",
    20,
    100
  );

  doc.save(
    `${projectName || "premium-report"}.pdf`
  );

};

const generateShareImage = async () => {

  if (!resultRef.current) return;

  const canvas =
  await html2canvas(
    resultRef.current,
    {
      backgroundColor: "#0F1115",
      useCORS: true,
    }
  );

  const image =
    canvas.toDataURL("image/png");

  const link =
    document.createElement("a");

  link.href = image;

  link.download =
    "my-house-cost-ng.png";

  link.click();

};

const handleFullReportPayment = () => {

  setPaymentAmount(10000);

  setEmailModalType("full");

  setShowEmailModal(true);

};

const handlePremiumPayment = () => {

  setPaymentAmount(30000);

  setEmailModalType("premium");

  setShowEmailModal(true);

};

const paystackProps = {
  email,
  amount,
  publicKey,

  text: "Continue to Payment",

  onSuccess: async () => {

  await saveReport();

  await sendReportEmail();

  generatePDF();

  alert(
    "Payment Successful!"
    
  );

  setShowEmailModal(false);

  if (emailModalType === "full") {

  window.location.href =
    "/full-report";

}

if (emailModalType === "premium") {

  window.location.href = "/premium-dashboard";

}

},

  onClose: () => {
    alert("Transaction Cancelled");
  },
};
const foundation = result ? result * 0.18 : 0;

const structure = result ? result * 0.35 : 0;

const finishes = result ? result * 0.28 : 0;

const services = result ? result * 0.12 : 0;

const addonCost =

  (addFence ? 2500000 : 0) +

  (addBQ ? 7000000 : 0) +

  (addPool ? 5000000 : 0) +

  (luxuryRoof ? 3500000 : 0);

const totalWithAddons =
  (result || 0) + addonCost;

const comparisonData = [

  {
    finish: "Basic",
    multiplier: 1,
  },

  {
    finish: "Standard",
    multiplier: 1.25,
  },

  {
    finish: "Luxury",
    multiplier: 1.6,
  },

];

const income =
  Number(monthlyIncome) || 0;

const savings =
  Number(currentSavings) || 0;

const yearlyIncome =
  income * 12;

const affordabilityYears =
  yearlyIncome > 0
    ? (
        totalWithAddons /
        yearlyIncome
      ).toFixed(1)
    : null;

const affordabilityScore =
  yearlyIncome > 0
    ? Math.min(
        100,
        Math.round(
          (yearlyIncome /
            totalWithAddons) *
            1000
        )
      )
    : 0;


const smartInsights = [

  finish === "Luxury"
    ? `Using Standard finish instead of Luxury could save you approximately ₦${Math.round(result! * 0.18).toLocaleString()}`

    : `Luxury finishing increases long-term property value significantly`,

  addBQ
    ? "Adding a Boys Quarters may increase project duration by 2 months"

    : "Adding a BQ can improve rental value and resale potential",

  addFence
    ? "Fence installation is cheaper during early construction stages"

    : "Perimeter fencing improves site security during construction",

  addPool
    ? "Swimming pools significantly increase maintenance costs"

    : "Luxury outdoor features improve premium property appeal",

];

const detailedBreakdown = [
  {
    category: "Foundation",
    items: [
      {
        name: "Excavation",
        cost: result ? result * 0.03 : 0,
      },

      {
        name: "Concrete",
        cost: result ? result * 0.05 : 0,
      },

      {
        name: "Reinforcement",
        cost: result ? result * 0.04 : 0,
      },
    ],
  },

  {
    category: "Structure",
    items: [
      {
        name: "Blocks & Blockwork",
        cost: result ? result * 0.08 : 0,
      },

      {
        name: "Columns & Beams",
        cost: result ? result * 0.07 : 0,
      },

      {
        name: "Roofing",
        cost: result ? result * 0.09 : 0,
      },
    ],
  },

  {
    category: "Finishes",
    items: [
      {
        name: "Floor Tiles",
        cost: result ? result * 0.06 : 0,
      },

      {
        name: "Painting",
        cost: result ? result * 0.03 : 0,
      },

      {
        name: "POP Ceiling",
        cost: result ? result * 0.04 : 0,
      },
    ],
  },

  {
    category: "Services",
    items: [
      {
        name: "Electrical",
        cost: result ? result * 0.05 : 0,
      },

      {
        name: "Plumbing",
        cost: result ? result * 0.04 : 0,
      },

      {
        name: "Water Installation",
        cost: result ? result * 0.03 : 0,
      },
    ],
  },
];

const finishMultipliers: Record<string, number> = {
  Basic: 0.85,
  Standard: 1,
  Luxury: 1.4,
};
const locationRates: Record<string, number> = {
  Lekki: 450000,
  Ajah: 350000,
  Ikorodu: 250000,
  Ikeja: 400000,
  Yaba: 380000,
  Abuja: 420000,
  "Port Harcourt": 390000,
};

const contractors = [

  {
    name: "BuildPro Nigeria",
    location: "Lagos",
    specialty: "Luxury Duplex Construction",
  },

  {
    name: "Prime Structure Ltd",
    location: "Abuja",
    specialty: "Commercial Buildings",
  },

  {
    name: "Elite Homes",
    location: "Port Harcourt",
    specialty: "Residential Projects",
  },

];

  return (
    <main className="min-h-screen bg-[#0F1115] text-white flex items-center justify-center px-4 py-10">

      <div className="w-full max-w-md">

        {/* Logo */}
        <div className="mb-8">
         <div className="flex items-center gap-3">

  <div className="bg-[#1A1D24] p-3 rounded-2xl border border-[#2A2F3A]">
    <House className="text-[#D4A84F]" size={34} />
  </div>

  <h1 className="text-3xl font-bold leading-tight">
    My House <span className="text-[#D4A84F]">Cost NG</span>
  </h1>

</div>

          <p className="text-gray-400 mt-1">
            Smart Building Cost Estimator
          </p>
        </div>

        {/* FORM SCREEN */}
        {!showResult && (

          <div className="bg-[#1A1D24] rounded-[32px] p-6 border border-[#2A2F3A] shadow-2xl">

            {/* Heading */}
            <div className="mb-8">
              <h2 className="text-4xl font-bold leading-tight">
                Estimate your building cost in seconds
              </h2>

              <p className="text-gray-400 mt-4">
                Fast. Accurate. Reliable.
              </p>
            </div>

            {/* Form */}
            <div className="space-y-5">

              {/* Project Name */}
              <div>
                <label className="text-sm text-gray-300">
                  Project Name
                </label>

                <input
                  type="text"
                  placeholder="e.g. 4 Bedroom Duplex"
                  className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
                  onChange={(e) => setProjectName(e.target.value)}
                />
              </div>

<label className="text-sm text-gray-300">
  Select Project/House
</label>

<select
  value={buildingCategory}
  onChange={(e) =>
    setBuildingCategory(e.target.value)
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>

  {Object.keys(buildingTypes).map(
    (category) => (

      <option
        key={category}
        value={category}
      >
        {category}
      </option>

    )
  )}

</select>

<label className="text-sm text-gray-300">
  Select Type
</label>

<select
  value={buildingSubtype}
  onChange={(e) =>
    setBuildingSubtype(e.target.value)
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>

  {buildingTypes[
    buildingCategory as keyof typeof buildingTypes
  ]?.map((type) => (

    <option
      key={type}
      value={type}
    >
      {type}
    </option>

  ))}

</select>

<label className="text-sm text-gray-300">
  Select No of Bedroom
</label>

{buildingCategory !== "HighRise" && (

<select
  value={bedrooms}
  onChange={(e) =>
    setBedrooms(Number(e.target.value))
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>

  <option value={1}>
    1 Bedroom
  </option>

  <option value={2}>
    2 Bedroom
  </option>

  <option value={3}>
    3 Bedroom
  </option>

  <option value={4}>
    4 Bedroom
  </option>

  <option value={5}>
    5 Bedroom
  </option>

  <option value={6}>
    6+ Bedroom
  </option>

</select>
)}

{(buildingCategory === "Apartment" ||
  buildingCategory === "HighRise") && (

<select
  value={units}
  onChange={(e) =>
    setUnits(Number(e.target.value))
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>

  <option value={1}>
    1 Unit
  </option>

  <option value={2}>
    2 Units
  </option>

  <option value={4}>
    4 Units
  </option>

  <option value={6}>
    6 Units
  </option>

  <option value={8}>
    8+ Units
  </option>

</select>

)}

{buildingCategory !== "Bungalow" &&
 buildingCategory !== "Traditional" && (

<label className="text-sm text-gray-300">
  Select Floor
</label>

)}
{buildingCategory !== "Bungalow" &&
 buildingCategory !== "Traditional" && (

<select
  value={floors}
  onChange={(e) =>
    setFloors(Number(e.target.value))
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>

  <option value={1}>
    1 Floor
  </option>

  <option value={2}>
    2 Floors
  </option>

  <option value={3}>
    3 Floors
  </option>

  <option value={4}>
    4 Floors
  </option>

  <option value={5}>
    5+ Floors
  </option>

</select>

)}

              {/* State */}
              <div>
                <label className="text-sm text-gray-300">
                  Select State
                </label>

                <select
                  className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
                  onChange={(e) => setState(e.target.value)}
                >
                  <option value="">Select State</option>

<option>Lagos</option>
<option>Abuja</option>
<option>Rivers</option>
<option>Kano</option>
<option>Enugu</option>
<option>Ibadan</option>
<option>Kaduna</option>
<option>Kwara</option>
<option>Ogun</option>
                </select>
              </div>

              {/* Location */}
<div>
  <label className="text-sm text-gray-300">
    Select Location
  </label>

  <select
    className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
    onChange={(e) => setLocation(e.target.value)}
  >
    <option value="">
  Select Location
</option>

{stateLocations[state]?.map((location) => (

  <option
    key={location}
    value={location}
  >
    {location}
  </option>

))}

  </select>
</div>
{/* Finish Level */}
<div>
  <label className="text-sm text-gray-300">
    Finish Level
  </label>

  <select
    className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
    onChange={(e) => setFinish(e.target.value)}
  >
    <option>Standard</option>
    <option>Basic</option>
    <option>Luxury</option>
  </select>
</div>

              {/* Land Size */}
              <div>
                <label className="text-sm text-gray-300">
                  Land Size
                </label>

                <input
                  type="number"
                  placeholder="e.g. 500"
                  className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
                  onChange={(e) => setSize(e.target.value)}
                />
                <select
  value={sizeUnit}
  onChange={(e) =>
    setSizeUnit(e.target.value)
  }
  className="w-full mt-3 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
>
  <option value="SQM">
    Square Meter (SQM)
  </option>

  <option value="FT">
    Square Foot (FT²)
  </option>
</select>
              </div>

              {/* Button */}
              <button
                onClick={() => {
                 const baseCost =
  buildingBaseCosts[buildingSubtype]

const stateMultiplier =
  stateMultipliers[state] || 1;

const finishMultiplier =
  finishMultipliers[finish] || 1;

const convertedSize =
  sizeUnit === "FT"
    ? Number(size) / 10.764
    : Number(size);

    const bedroomMultiplier =
  bedroomMultipliers[bedrooms] || 1;

  const floorMultiplier =
  floorMultipliers[floors] || 1;

  const foundationMultiplier =
  foundationMultipliers[
    buildingCategory
  ] || 1;

  const unitMultiplier =
  unitMultipliers[units] || 1;

const estimatedCost =
  convertedSize *
  baseCost *
  stateMultiplier *
  finishMultiplier *
  bedroomMultiplier *
  floorMultiplier *
  foundationMultiplier *
  unitMultiplier;

                  setResult(estimatedCost);

                  setShowResult(true);
                  window.scrollTo({
  top: 0,
  behavior: "smooth",
});
                }}
                className="w-full bg-[#D4A84F] text-black p-4 rounded-2xl font-bold text-lg mt-4 hover:scale-[0.98] transition-all duration-200"
              >
                GET ESTIMATE →
              </button>

            </div>
          </div>

        )}

        {/* RESULT SCREEN */}
        {showResult && result && (

          <div
  ref={resultRef}
  className="bg-[#1A1D24] rounded-[32px] p-6 border border-[#2A2F3A] shadow-2xl"
>

            {/* Back Button */}
            <button
              onClick={() => setShowResult(false)}
              className="mb-6 text-sm text-gray-400"
            >
              ← Back
            </button>

            {/* Result Header */}
            <div className="text-center mb-6">

              <p className="text-green-400 text-sm">
                Estimate Completed ✅
              </p>

              <h2 className="text-5xl font-bold mt-4">

  ₦
 <CountUp
  end={totalWithAddons}
  duration={2}
  separator=","
/>
</h2>

              <p className="text-gray-400 mt-2">
                Estimated total cost in {location || state}
              </p>

            </div>

            {/* Breakdown */}
            <div className="space-y-4 border-t border-[#2A2F3A] pt-4">

              <div className="flex justify-between">
                <span className="text-gray-400">Foundation</span>
                <span>
  ₦{foundation.toLocaleString()}
</span>
              </div>

              <div className="flex justify-between">
                <span className="text-gray-400">Structure</span>
                <span>
  ₦{structure.toLocaleString()}
</span>
              </div>

              <div className="flex justify-between">
                <span className="text-gray-400">Finishes</span>
                <span>
  ₦{finishes.toLocaleString()}
</span>
              </div>

              <div className="flex justify-between">
                <span className="text-gray-400">Services</span>
                <span>
  ₦{services.toLocaleString()}
</span>
              </div>

            </div>

            {/* Insight Box */}
            <div className="bg-[#2A2418] border border-[#4A3A1A] rounded-2xl p-4 mt-6">
              <p className="text-sm text-[#D4A84F]">
              💡 Choosing {finish} finishing affects the total project cost significantly.
              </p>
            </div>

{/* Action Buttons */}
<div className="grid grid-cols-2 gap-3 mt-6">

  <button
  onClick={() => {

    const shareText =
      `My building project in ${location} is estimated at ₦${totalWithAddons.toLocaleString()} using My House Cost NG 🏠`;

    if (navigator.share) {

      navigator.share({
        title: "My House Cost NG",
        text: shareText,
      });

    } else {

      navigator.clipboard.writeText(
        shareText
      );

      alert(
        "Result copied to clipboard!"
      );

    }

  }}
  className="bg-[#D4A84F] text-black rounded-2xl p-4 font-semibold"
>
  Share Result
</button>

  <button
    onClick={() => setShowResult(false)}
    className="border border-[#2A2F3A] rounded-2xl p-4"
  >
    Adjust Estimate
  </button>

</div>

{/* What-If Simulator */}
<div className="bg-[#1A1D24] border border-[#2A2F3A] rounded-[32px] p-6 mt-6">

  <div className="flex items-center justify-between">

    <div>

      <h3 className="text-2xl font-bold">
        What-If Simulator
      </h3>

      <p className="text-gray-400 mt-1">
        Customize your project
      </p>

    </div>

    <div className="text-3xl">
      🎛️
    </div>

  </div>

  <div className="space-y-4 mt-6">

    {/* Fence */}
    <label className="flex items-center justify-between border border-[#2A2F3A] rounded-2xl p-4 cursor-pointer">

      <div>

        <p className="font-semibold">
          Add Fence
        </p>

        <p className="text-sm text-gray-400">
          + ₦2,500,000
        </p>

      </div>

      <input
        type="checkbox"
        checked={addFence}
        onChange={() =>
          setAddFence(!addFence)
        }
      />

    </label>

    {/* BQ */}
    <label className="flex items-center justify-between border border-[#2A2F3A] rounded-2xl p-4 cursor-pointer">

      <div>

        <p className="font-semibold">
          Add Boys Quarters
        </p>

        <p className="text-sm text-gray-400">
          + ₦7,000,000
        </p>

      </div>

      <input
        type="checkbox"
        checked={addBQ}
        onChange={() =>
          setAddBQ(!addBQ)
        }
      />

    </label>

    {/* Pool */}
    <label className="flex items-center justify-between border border-[#2A2F3A] rounded-2xl p-4 cursor-pointer">

      <div>

        <p className="font-semibold">
          Add Swimming Pool
        </p>

        <p className="text-sm text-gray-400">
          + ₦5,000,000
        </p>

      </div>

      <input
        type="checkbox"
        checked={addPool}
        onChange={() =>
          setAddPool(!addPool)
        }
      />

    </label>

    {/* Roof */}
    <label className="flex items-center justify-between border border-[#2A2F3A] rounded-2xl p-4 cursor-pointer">

      <div>

        <p className="font-semibold">
          Luxury Roofing
        </p>

        <p className="text-sm text-gray-400">
          + ₦3,500,000
        </p>

      </div>

      <input
        type="checkbox"
        checked={luxuryRoof}
        onChange={() =>
          setLuxuryRoof(!luxuryRoof)
        }
      />

    </label>

  </div>

</div>

{/* Cost Comparison */}
<div className="bg-[#1A1D24] border border-[#2A2F3A] rounded-[32px] p-6 mt-6">

  <div className="flex items-center justify-between">

    <div>

      <h3 className="text-2xl font-bold">
        Cost Comparison
      </h3>

      <p className="text-gray-400 mt-1">
        Compare finishing levels
      </p>

    </div>

    <div className="text-3xl">
      📊
    </div>

  </div>

  <div className="space-y-4 mt-6">

    {comparisonData.map((item) => (

      <div
        key={item.finish}
        className="border border-[#2A2F3A] rounded-2xl p-4 flex items-center justify-between"
      >

        <div>

          <p className="font-semibold">
            {item.finish}
          </p>

          <p className="text-sm text-gray-400 mt-1">
            Estimated project cost
          </p>

        </div>

        <p className="font-bold text-[#D4A84F]">

          ₦
          {result
            ? Math.round(
                result * item.multiplier
              ).toLocaleString()
            : "0"}

        </p>

      </div>

    ))}

  </div>

</div>

{/* Affordability Engine */}
<div className="bg-[#1A1D24] border border-[#2A2F3A] rounded-[32px] p-6 mt-6">

  <div className="flex items-center justify-between">

    <div>

      <h3 className="text-2xl font-bold">
        Affordability Engine
      </h3>

      <p className="text-gray-400 mt-1">
        Analyze your financial readiness
      </p>

    </div>

    <div className="text-3xl">
      💰
    </div>

  </div>

  <div className="space-y-4 mt-6">

    {/* Monthly Income */}
    <input
      type="number"
      placeholder="Monthly Income (₦)"
      value={monthlyIncome}
      onChange={(e) =>
        setMonthlyIncome(e.target.value)
      }
      className="w-full bg-[#0F1115] border border-[#2A2F3A] rounded-2xl p-4 outline-none"
    />

    {/* Savings */}
    <input
      type="number"
      placeholder="Current Savings (₦)"
      value={currentSavings}
      onChange={(e) =>
        setCurrentSavings(e.target.value)
      }
      className="w-full bg-[#0F1115] border border-[#2A2F3A] rounded-2xl p-4 outline-none"
    />

  </div>

  {income > 0 && (

    <div className="mt-6 space-y-4">

      <div className="border border-[#2A2F3A] rounded-2xl p-4">

        <p className="text-sm text-gray-400">
          Estimated Completion Time
        </p>

        <p className="text-2xl font-bold mt-2">

          {affordabilityYears} years

        </p>

      </div>

      <div className="border border-[#2A2F3A] rounded-2xl p-4">

        <p className="text-sm text-gray-400">
          Financial Readiness Score
        </p>

        <p className="text-2xl font-bold mt-2 text-[#D4A84F]">

          {affordabilityScore}%

        </p>

      </div>

      <div className="border border-[#2A2F3A] rounded-2xl p-4">

        <p className="text-sm leading-relaxed text-gray-300">

          {affordabilityScore > 70

            ? "You are financially positioned to execute this project comfortably."

            : affordabilityScore > 40

            ? "This project may require phased construction or financing support."

            : "This project may be financially aggressive at your current income level."}

        </p>

      </div>

    </div>

  )}

</div>

{/* AI Smart Insights */}
<div className="bg-[#1A1D24] border border-[#2A2F3A] rounded-[32px] p-6 mt-6">

  <div className="flex items-center justify-between">

    <div>

      <h3 className="text-2xl font-bold">
        AI Smart Insights
      </h3>

      <p className="text-gray-400 mt-1">
        Intelligent project recommendations
      </p>

    </div>

    <div className="text-3xl">
      🧠
    </div>

  </div>

  <div className="space-y-4 mt-6">

    {smartInsights.map((insight, index) => (

      <div
        key={index}
        className="border border-[#2A2F3A] rounded-2xl p-4"
      >

        <p className="text-sm leading-relaxed text-gray-300">

          {insight}

        </p>

      </div>

    ))}

  </div>

</div>

            {/* Packages */}
            <div className="space-y-3 mt-6">
              <button onClick={() => {

  setPaymentAmount(3000);

  setEmailModalType("basic");

  setShowEmailModal(true);

}}
              className="w-full border border-[#2A2F3A] rounded-2xl p-4 text-left">
                <p className="font-semibold">
                  Basic Report + PDF
                </p>

                <p className="text-sm text-gray-400 mt-1">
                  Detailed breakdown + PDF
                </p>

                <p className="mt-2 font-bold text-[#D4A84F]">
                  ₦3,000
                </p>
              </button>

              <button
  onClick={handleFullReportPayment}
  className="w-full border border-[#2A2F3A] rounded-2xl p-4 text-left"
>
                <p className="font-semibold">
                  Full Report + PDF + Email
                </p>

                <p className="text-sm text-gray-400 mt-1">
                  PDF + planning guide
                </p>
<div className="mt-4 space-y-2 text-sm text-gray-400">

  <p>• Detailed BOQ Breakdown</p>

  <p>• Labour & Material Split</p>

  <p>• Roofing Estimate</p>

  <p>• Plumbing & Electrical Cost</p>

  <p>• Premium PDF Report</p>

</div>

                <p className="mt-2 font-bold text-[#D4A84F]">
                  ₦10,000
                </p>
              </button>

              <button
  onClick={handlePremiumPayment}
  className="w-full border border-[#2A2F3A] rounded-2xl p-4 text-left"
>
                <p className="font-semibold">
                  Premium + Contractors
                </p>

  <p className="text-sm text-gray-400 mt-1">
    Connect with verified builders
  </p>

  <div className="relative mt-4">

    {/* Blur Layer */}
    <div className="blur-sm opacity-60 pointer-events-none">

      <div className="space-y-3">

        {contractors.map((contractor) => (

          <div
            key={contractor.name}
            className="border border-[#2A2F3A] rounded-2xl p-3"
          >

            <p className="font-semibold">
              {contractor.name}
            </p>

            <p className="text-sm text-gray-400 mt-1">
              {contractor.location}
            </p>

            <p className="text-sm text-[#D4A84F] mt-1">
              {contractor.specialty}
            </p>

          </div>

        ))}

      </div>

    </div>

    {/* Overlay */}
    <div className="absolute inset-0 flex items-center justify-center">

      <div className="bg-[#0F1115]/90 border border-[#2A2F3A] rounded-2xl px-6 py-5 text-center">

        <p className="text-2xl">
          🔒
        </p>

        <p className="font-bold mt-2">
          Unlock Premium
        </p>

        <div
  className="mt-4 bg-[#D4A84F] text-black px-5 py-3 rounded-xl font-semibold"
>
  Upgrade
</div>

      </div>

    </div>

  </div>

  <p className="mt-4 font-bold text-[#D4A84F]">
    ₦30,000
  </p>

</button>

            </div>

          </div>

        )}
{/* Email Modal */}
{showEmailModal && (

  <div className="fixed inset-0 bg-black/70 flex items-center justify-center px-4 z-50">

    <div className="bg-[#1A1D24] w-full max-w-md rounded-[32px] p-6 border border-[#2A2F3A]">

      <h2 className="text-2xl font-bold">
        Unlock Your Report
      </h2>

      <p className="text-gray-400 mt-2">
        Enter your email to continue
      </p>

      {/* Email Input */}
      <GoogleSignIn />
      <div className="mt-6">

        <label className="text-sm text-gray-300">
          Email Address
        </label>

        <input
          type="email"
          placeholder="you@example.com"
          className="w-full mt-2 p-4 rounded-2xl bg-[#0F1115] border border-[#2A2F3A] outline-none"
          onChange={(e) => setEmail(e.target.value)}
        />

      </div>

      {/* Buttons */}
      <div className="grid grid-cols-2 gap-3 mt-6">

        <button
          onClick={() => setShowEmailModal(false)}
          className="border border-[#2A2F3A] rounded-2xl p-4"
        >
          Cancel
        </button>

        <PaystackButton
  {...paystackProps}
  className="bg-[#D4A84F] text-black rounded-2xl p-4 font-semibold cursor-pointer"
/>

      </div>

    </div>

  </div>

)}

        {/* Features */}
        <div className="grid grid-cols-3 gap-4 mt-8">

          <div className="text-center">
            <div className="text-3xl">🛡️</div>

            <h3 className="mt-2 font-semibold">
              Accurate
            </h3>

            <p className="text-xs text-gray-500 mt-1">
              Real market data
            </p>
          </div>

          <div className="text-center">
            <div className="text-3xl">⚡</div>

            <h3 className="mt-2 font-semibold">
              Instant
            </h3>

            <p className="text-xs text-gray-500 mt-1">
              Results in seconds
            </p>
          </div>

          <div className="text-center">
            <div className="text-3xl">🔒</div>

            <h3 className="mt-2 font-semibold">
              Secure
            </h3>

            <p className="text-xs text-gray-500 mt-1">
              Your data is safe
            </p>
          </div>

        </div>

        {/* Footer */}
        <p className="text-center text-gray-500 text-sm mt-10">
          Built for Nigeria 🇳🇬
        </p>

      </div>

    </main>
  );
}